
variants = {
'aberi': {'aberi', 'abheri'},
'abogi': {'abogi', 'abhogi'},
'ahiri': {'ahiri'},
'amritavarshini': {'amruthavarshini','amr̥tavarṣiṇi',  'amirthavarshini', 'amruta varshini', 'amrtha varshini', 'amritavarshini', 'amrutavarshini', 'amrutha varshini', 'amritha varshini', 'amirtha varshini', 'amrthavarshini', 'amrtavarshini', 'amrta varshini'},
'anandabairavi': {'ananda bhairavi', 'anandabhairavi', 'anandabairavi', 'anandabhairavii', 'anandabairavi', 'ananda bairavi'},
'andolika': {'andolika', 'andholika'},
'arabi': {'arabi', 'aarabhi', 'arabhi'},
'asaveri': {'asaveri', 'asavri'},
'atana': {'athana', 'atana'},
'bageshri': {'bhageshri', 'bageshri'},
'bahudari': {'bahudari', 'bahudhari'},
'bairavi': {'bhairavi/', 'bairavi', 'bhairavi', 'bhairavii'},
'bauli': {'bauli', 'bhowli', 'bhauli', 'bowli'},
'bavani': {'bhavani', 'bavani'},
'begada': {'begada', 'begade'},
'behag': {'behag', 'bihag'},
'bhavapriya': {'bhavapriya'},
'bilahari': {'bilahari'},
'bimpalas': {'bhimplas', 'bhimpalas', 'bimpalas'},
'bindumalini': {'bindumalini'},
'brindavanasaranga': {'brindavanasaranga', 'brindavana saranga', 'vrndavanasaaranga', 'brindava saranga', 'vrndavana saranga', 'vrndavanasaranga'},
'brindavani': {'brindavani'},
'budamanohari': {'budhamanohari', 'budamanohari'},
'bupalam': {'bupalam', 'bhoopalam', 'bhupalam'},
'bushavali': {'bhushavali', 'bushavali'},
'buvanagandari': {'buvanagandari', 'bhuvanagandari'},
'chayagowla': {'cayagowla', 'chayagowla', 'cayagowlai', 'chayagowlai'},
'cayaranjani': {'cayaranjani', 'chayaranjani'},
'chakravakam': {'chakravakham', 'chakravakam', 'chakravaham', 'cakravakam'},
'chalanatta': {'chalanattaii', 'chala natta', 'chala nattai', 'chalanatta', 'chalanattai', 'calanattai', 'cala nattai', 'calanatta'},
'chandrajyoti': {'chandra jyoti', 'chandrajyoti', 'chandrajyothi', 'candrajyoti'},
'chandrakauns': {'chandra kauns', 'chandrakauns', 'candrakowns'},
'charukesi': {'charukesi', 'carukesi', 'charukeshi', 'carukeshi'},
'chauka': {'chauka'},
'chayatarangini': {'chayatarangini', 'chayata rangini', 'chayata ranjani', 'chayatharangini', 'chhayaatarangini'},
'chitrambari': {'chitrambari', 'citrambari'},
'curnikavinodini': {'curnikavinodini'},
'danyasi': {'danyasi', 'dhanyasi'},
'darbar': {'darbar', 'durbar'},
'darbarikanada': {'darbari kannada', 'darbari kanada', 'darbarikanada'},
'darmavati': {'darmavati', 'dharmavathy', 'dharmavathi', 'dharmavati'},
'datuvardani': {'datuvardani', 'datuvardhani'},
'desh': {'desh', 'des', 'deshh'},
'deshyatodi': {'deshyatodi', 'deshikatodi', 'desiyatodi', 'desikatodi', 'deshikathodi', 'deshiyathodi', 'desiyathodi'},
'devagandari': {'devagandari', 'devagandhari', 'devagandharam', 'devgandhari'},
'devamanohari': {'deva manohari', 'devamanohari'},
'devapriya': {'devakriya', 'devapriya'},
'dhenuka': {'dhenuka', 'denuka'},
'durga': {'durga'},
'dwijavanti': {'dwijavanti', 'dvijavanti', 'dwijavanthi'},
'faras': {'paras', 'faras', 'pharas', 'faraz', 'pharaju', 'pharaj'},
'gamakapriya': {'gamakakriya', 'gamakapriya'},
'gamanashrama': {'gamanashrama'},
'gambiranatta': {'gambheera nattai', 'gambheera natta', 'gambiranatta', 'gambheeranattai', 'gambheeranatta', 'gambhira nattai', 'gambhiranattai'},
'ganamurti': {'ganamoorthi', 'ganamurti', 'ganamurthi'},
'ganapatim': {'ganapathim', 'ganapatim'},
'gangayabhushani': {'gangayabhushani', 'gangayabhushhani', 'gangeyabhushani', 'gangeyabhushhani', 'gangayabhooshani', 'gangayabhooshhani', 'gangeyabhooshani', 'gangeyabhooshhani'},   
'garudadwani': {'garudadhwani', 'garudadwani', 'garudadhvani'},
'gaudamalhar': {'gaudamalhar'},
'gaula': {'gaulai', 'gaula', 'gowla', 'gowlai'},
'gaulipantu': {'gaulipantu', 'gowlipantu'},
'gauri': {'gauri', 'gowri'},
'gaurimanohari': {'gowrimanohari', 'gowri manohari', 'gauri manohari', 'gaurimanohari'},
'gaurivelavali': {'gaurivelavali'},
'gavambodhi': {'gavambodhi'},
'ghanta': {'ghanta', 'ganta'},
'gopriya': {'gopriya'},
'hamirkalyani': {'hameer kalyani', 'hameerkalyani', 'hamirkalyani', 'hamir kalyani'},
'hamsadwani': {'hamsadwani', 'hamsadhvani', 'hamsadhwani'},
'hamsanadam': {'hamsanadam', 'hamsanada'},
'hamsanandi': {'hamsanandi', 'hamsanadhi'},
'hamsavinodini': {'hamsavinodini'},
'harikamboji': {'harikamboji', 'hari kambhoji', 'harikambhoji'},
'hemavati': {'hemavathy', 'hemavathi', 'hemavati'},
'hindolam': {'hidola', 'hindolam', 'hindola', 'hindolamm', 'hindolammm'},
'hindolavasantha': {'hindolavasantha', 'hindola vasantha', 'hindolavasanta', 'hindola vasanta'},
'hindustanibehag': {'hindustanibehag', 'hindustani behag'},
'hindustanibhairavi': {'hindustanibhairavi', 'hindustani bhairavi'},
'hindustanigandhari': {'hindustanigandhari', 'hindustani gandhari'},
'hindustanikapi': {'hindustanikapi', 'hindustani kapi'},
'hindustanipilu': {'hindustanipilu', 'hindustani pilu'},
'hindustanitodi': {'hindustanitodi', 'hindustani todi'},
'huseni': {'hhuseni', 'huseni', 'useni'},
'jaganmohini': {'jagan mohini', 'jaganmohanam', 'jaganmohini', 'jaganmohana'},
'janaranjani': {'jana ranjani', 'janaranjani'},
'janasammodini': {'janasammodini', 'janasammodhini'},
'janatodi': {'janatodi'},
'jayamanohari': {'jayamanohari', 'jaya manohari'},
'jayantashri': {'jayanthashri', 'jayantashri'},
'jingala': {'jingala'},
'jog': {'jog'},
'jonpuri': {'jaunpuri', 'jonpuri'},
'jyotiswarupini': {'jyotiswarupini', 'jyotiswaroopini', 'jyoti swarupini', 'jyoti swaroopini'},
'kadanakutuhalam': {'kadanakadanakuthoohalam', 'kuthuhala', 'kadanakuthoohalam', 'kathanakadanakuthoohalamm', 'kadanakutuhalam', 'kadana kuthoohalam'},
'kalavati': {'kalavathy', 'kalavathi', 'kalavati', 'kalaavathi', 'kalaavati'},
'kalgada': {'kalgada'},
'kalyanavasantam': {'kalyanavasantham', 'kalyana vasantham', 'kalyanavasantam', 'kalyana vasantam'},
'kalyani': {'kalyaani', 'kalyani', 'mecakalyaani', 'mecakalyani','mechakalyaani', 'mechakalyani', 'meca kalyaani', 'meca kalyani','mecha kalyaani', 'mecha kalyani'},
'kamalamanohari': {'kamalamanohari', 'kamala manohari'},
'kamas': {'kamas', 'khamas'},
'kamboji': {'kambhoji', 'kambhodhi', 'kamboji', 'kambodi', 'kambodhi'},
'kanada': {'kanada', 'kaanada'},
'kanakangi': {'kanakangi'},
'kannada': {'kannada'},
'kannadagaula': {'kannadagaula', 'kannada gowlai', 'kannadagowlai'},
'kanta': {'kanta'},
'kantamani': {'kantamani', 'kanthamani'},
'kapinarayani': {'kapinarayani', 'kapi narayani'},
'kapi': {'kapi', 'kaapi'},
'kapinarayani': {'kapinarayani'},
'karaharapriya': {'karaharapriya', 'kharaharapriya'},
'karnaranjani': {'karnaranjani', 'karna rajani', 'karna ranjani'},
'karnatakakapi': {'karnatakakapi', 'karnataka kapi'},
'karnatakasuddasaveri': {'karnatakasuddasaveri', 'karnataka suddha saveri','karnatakasuddhasaveri', 'karnataka sudda saveri'},
'katyayani': {'katyayani', 'kathyayani'},
'kedaragaula': {'kedara gowlai', 'kedaragaula', 'kedaragowla', 'kedara gowla', 'kedaragowlai','harikedara gowlai', 'harikedaragaula', 'harikedaragowla', 'hari kedara gowla', 'harikedaragowlai'},
'kedaram': {'kedrarm', 'kedaram'},
'kiravani': {'kiravani', 'kheeravani', 'keeravani', 'keerawani', 'kiranavali', 'keervani'},
'kokilapanchamam': {'kokilapanchamam'},
'kokilapriya': {'kokilapriya'},
'kosalam': {'kosalam', 'koshalam'},
'kumudapriya': {'kumudakriya', 'kumudapriya'},
'kuntalavarali': {'kunthala varali', 'kuntala varali', 'kunthalavarali', 'kuntalavarali'},
'kurunji': {'kurunji', 'kurinji'},
'lalita': {'lalitha', 'lalita'},
'latangi': {'lathangi', 'latangi', "geetapriya", "gitapriya"},
'lavangi': {'lavangi'},
'madhukowns': {'madhukowns', 'madhukauns'},
'maduvanti': {'madhuvanti', 'maduvanti', 'madhuvanthi'},
'madyamavarali': {'madhyamavarali', 'madyamavarali'},
'madyamavati': {'madhyamavathi', 'madhyamavathy', 'madhyamavati', 'madhya mavathi', 'madyamavathi', 'madyamavati'},
'mahati': {'mahati'},
'malahari': {'malahari'},
'malavi': {'malavi'},
'malayamarutam': {'malaya marutham', 'malayamarutam', 'malayamarutham'},
'mand': {'mandu', 'maand', 'mand'},
'mandara': {'mandara', 'mandhara'},
'mandari': {'mandari'},
'manirangu': {'manirangu'},
'manjari': {'manjari'},
'manji': {'manji'},
'margadeshi': {'margadeshi'},
'mayamalavagaula': {'mayamalava gowlai', 'mayamalavagaula', 'mayamalavagowlai', 'mayamalavagowla'},
'megaranjani': {'megha ranjani', 'megharanjani', 'megaranjani', 'mega ranjani'},
'mishrakapi': {'mishrakapi'},
'mohanakalyani': {'mohanam kalyani', 'mohanamkalyani', 'mohana kalyani', 'mohanakalyani'},
'mohanam': {'mohana', 'mohanam', 'mōhaṉam', 'mohanamm'},
'mukari': {'mukari', 'mukhari'},
'nadabrahma': {'naadabrahma', 'nadabrahma'},
'nadanamapriya': {'nadanamakriya', 'nadanamapriya'},
'nagagandari': {'nagagandari', 'nagagandhari', 'nagagandharai'},
'nagashwarali': {'nagashwarali', 'nagaswarali', 'nagaswaravali'},
'nalinakanti': {'nalinakanti', 'nalinakanthi'},
'narayanagaula': {'narayana gaula', 'narayanagaula'},
'narayani': {'narayani'},
'nariritigaula': {'nariritigaula', 'narireethigaula'},
'nasamani': {'nasamani'},
'nasikabushani': {'nasikabushani', 'nasikabhooshani', 'nasikabhusani', 'nasikabhushhani'},
'natabairavi': {'natabairavi', 'nata bhairavi', 'natta bhairavi', 'natabhairavi'},
'natakapriya': {'natakapriya'},
'natakurinji': {'nattaikurinji', 'natakurinji', 'nattaikuranji', 'nattakurinji', 'nattaikurunji', 'nattaiikuranji', 'nattaiikurinji', 'nattai kurinji', 'natakuranji', 'nattai kurinji'},
'natta': {'nata', 'nattai', 'naata', 'natta', 'nattaii', 'naatha', 'naatta'},
'navarasakanada': {'navarasakanada', 'navarasa kanada', 'navarasa kannada'},
'navroj': {'navroj'},
'nayaki': {'nayaki'},
'nilambari': {'neelambari', 'nīlāmbari', 'nilambari'},
'niroshta': {'niroshta'},
'nitimati': {'nitimati', 'neethimathi'},
'padi': {'padi'},
'pantuvarali': {'pantuvarali', 'pantu varali', 'panthu varali', 'panthuvarali', 'pantuvarali/kamavardhini', 'pantuvarali/pantuvarali', 'kamavardhini', 'panturvarali', 'pantuvarali/panturvarali', 'kamavardhini/pantuvarali', 'kamavardhani'},
'pavani': {'pavani'},
'pilu': {'pilu'},
'punnagavarali': {'punnagavarali'},
'purnachandrika': {'purnachandrika', 'poornachandrikaon', 'poornachandrika', 'poorna chandrika', 'purnacandrika', 'poornacandrika'},
'purnashadjam': {'poorna shadjam', 'poornashadjam', 'purnashadjam'},
'purvi': {'poorvi', 'purvi'},
'purvikalyani': {'purvi kalyani', 'purvikalyani', 'poorvikalyani', 'poorvi kalyani'},
'ragamalika': {'ragamalika', 'raagaaalikanavaragamaliga', 'ragamaalika', 'raga malika', 'raga maalika'},
'ragavardini': {'raagavardhini', 'ragavardini', 'ragavardhani'},
'ragavinodini': {'ragavinodini'},
'raghupriya': {'raghupriya', 'ragupriya'},
'rakeshri': {'rakeshri'},
'ramapriya': {'ramapriya', 'ramakriya'},
'ramkali': {'ramkali'},
'ranjani': {'ranjani', 'rajnani', 'ranjini'},
'rasali': {'rasali', 'rasaali'},
'rasavinodini': {'rasavinodini'},
'rasikapriya': {'rasikapriya', 'rasika priya'},
'ratipatipriya': {'ratipatipriya', 'rathipathipriya'},
'ratnakanti': {'ratnakanti', 'ratnakanthi'},
'ratnangi': {'ratnangi', 'rathnangi'},
'ratnavarali': {'ratnavarali', 'rathnavarali'},
'ravipriya': {'ravikriya', 'ravipriya'},
'revagupti': {'revagupti'},
'revati': {'revathi', 'revati'},
'rishabapriya': {'rishabha priya', 'rishabhapriya', 'rishabapriya', 'rishaba priya', 'rishhabapriya'},
'ritigaula': {'reethigoula', 'reethigaula', 'ritigaulai', 'reethigowlai', 'reethigowla', 'riti gaula', 'reethigwla', 'reetigaula', 'ritigaula', 'ritigowla'},
'rohini': {'rohini'},
'rudrapriya': {'rudrapriya'},
'rupavati': {'rupavati', 'roopavathi'},
'sahana': {'shahana', 'sahana'},
'salagabhairavi': {'salagabhairavi', 'salaga bhairavi'},
'sama': {'sama', 'saama', 'shyama', 'shyaama'},
'samanta': {'samantha', 'samanta'},
'saramati': {'saramathi', 'saramati'},
'saranga': {'saaranga', 'saranga'},
'sarasangi': {'sarasangi'},
'sarashwati': {'saraswathy', 'saraswati', 'sarashwati', 'saraswathi'},
'saraswatimanohari': {'saraswati manohari', 'saraswatimanohari'},
'saurashtram': {'sourashtram', 'saurashtram', 'sowrashtram', 'saurshtram', 'saurāṣṭram', 'saurasthram', 'sowrasthram'},
'saveri': {'saveri'},
'senchurutti': {'senchurutti', 'sencurutti', 'senjurutti', 'senjuruti', 'cenjuruti', 'chenjuruti', 'chenchurutti', 'shenjurutti', 'senjurutti'},
'seshadri': {'seshadri'},
'shankarabaranam': {'shankara bharanam', 'sankarabharana', 'shankarabharanamm', 'shankarabaranam', 'shankarabharanam', 'sankarabharanam', 'sankarabaranam', 'dhira shankarabharanam', 'dhirashankarabharanam', 'dheera shankarabharanam', 'dheerashankarabharanam'},
'shanmukapriya': {'chamaram', 'shanmukhapriya', 'shanmughapriya', 'shanmugapriya', 'shanmukapriya', 'camaram', 'shanmuka priya', 'shanmugha priya', 'shhanmugapriya'},
'shivakamboji': {'shivakamboji', 'shivakambhoji'},
'shivaranjani': {'siva ranjani', 'shivarangani', 'shivaranjani', 'sivaranjani', 'shiva ranjani'},
'shriraga': {'shriragam', 'shriraga', 'sree', 'shreeraga', 'sri', 'sriraga', 'shri', 'shri ragam', 'shree'},
'shriranjani': {'sriranjani', 'shreeraga', 'sreeranjani', 'sri ranjani', 'shrirangani', 'shriranjani'},
'shwaramanjari': {'shwaramanjari', 'swaramanjari', 'svaramanjari'},
'simhendramadyamam': {'simhendramadyamam', 'simhendra madhyamam', 'simhendramadhyamam', 'simhendra madyamam'},
'sindubairavi': {'sindhu bhairavi', 'sindubhairavi', 'sindhubhairavi', 'sindhubhairavii', 'sindubairavi', 'sindu bairavi', 'sindu bhairavi'},
'sohini': {'sohini', 'shohini'},
'subapantuvarali': {'subha pantuvarali', 'shubhapantuvarali', 'subhapantuvarali', 'subapantuvarali', 'shubhapantuvarali'},
'suddagandhari': {'suddagandhari', 'sudda gandhari', 'sudda gandari', 'suddagandari'},
'suddasarang': {'suddasarang', 'sudda sarang'},
'suddadanyasi': {'sudhadhanyasi', 'sudha dhanyasi', 'shudhadhanyasi', 'suddhadhanyasi', 'shudha dhanyasi', 'shuddhadhanyasi', 'suddha dhanyasi', 'shuddha dhanyasi', 'suddadanyasi', 'sudda danyasi'},
'suddasaveri': {'suddhasaveri', 'suddasaveri', 'suddha saveri', 'sudhasaveri', 'sudda saveri'},
'sumanasaranjani': {'sumanasa ranjani', 'sumanesa ranjani', 'sumanesaranjani', 'sumanasaranjani', 'sumanesharanjani'},
'sunadavinodini': {'sunadavinodini', 'sunaada vinodini'},
'suposhini': {'suposhini'},
'supradipam': {'supradeepam', 'supradipam'},
'supradipam': {'supradipam'},
'suraranjani': {'suraranjani'},
'surutti': {'surutti', 'suruti', 'shurutti', 'surati'},
'surya': {'surya'},
'suryakantam': {'suryakantam', 'suryakantham', 'sooryakantham', 'sooryakantam'},
'tanarupi': {'tanarupi', 'tanaroopi'},
'taranjani': {'tarangini', 'taranjani'},
'tilang': {'thilang', 'tilang'},
'todi': {'todi', 'thodi', 'hanuma todi', 'hanumatodi', 'hanumathodi'},
'udayaravichandrika': {'udayaravichandrika', 'udhayaravichandrika', 'udhayaravicandrika', 'udayaravicandrika', 'udaya ravichandrika', 'udhaya ravi candrika', 'udhaya ravi chandrika', 'udaya ravi candrika', 'udaya ravi chandrika'},
'urmika': {'urmika'},
'vachaspati': {'vachaspati', 'vaachaspathi', 'vacaspati'},
'vagadishwari': {'vagadishwari', 'vagadeeshwari', 'vagdeeswari'},
'vakulabaranam': {'vakulabaranam', 'vakulabharanam', 'vakhulabharanam'},
'valachi': {'valachi', 'valaji', 'valaci'},
'valila': {'valila'},
'vanaspati': {'vanaspati', 'vanaspati'},
'vandanadarini': {'vandanadharini', 'vandanadarini'},
'varali': {'varali'},
'varamu': {'varamu', 'suddahindolam', 'sudda hindolam', 'suddha hindolam'},
'vardini': {'vardhini', 'vardini'},
'varunapriya': {'varunapriya', 'varuna priya'},
'vasanta': {'vasanta', 'vasantha', 'vasanata'},
'vasantam': {'vasantam'},
'vasanti': {'vasanthi', 'vasanti'},
'vegavahini': {'vegavahini'},
'vijayanagari': {'vijayanagari', 'vijaya nagari', 'vijaya naagari', 'vijayanaagari'},
'vijayasaraswati': {'vijayasaraswati'},
'vijayashri': {'vijayashri'},
'viravasantam': {'viravasantham', 'viravasantam', 'vira vasantham', 'vira vasantam'},
'yadukulakamboji': {'yadukula kambhoji', 'yadukula kamboji', 'yadhukulacalmbodhi', 'yadhukula kambodhi', 'yadukulakamboji', 'yadukulakambhoji'},
'yagapriya': {'yagapriya'},
'yamunakalyani': {'yamunakalyani', 'yamuna kalyani'},
}


